# Generated by Django 4.2 on 2023-06-24 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donor',
            new_name='Donor_detail',
        ),
    ]
