# Generated by Django 4.2 on 2023-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_rename_donor_donor_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_detail',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
