# Generated by Django 4.2 on 2023-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_donor_detail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_detail',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
